### PR TITLE
Publish reports from travis

### PR DESCRIPTION
**Pull request by wtoorop**
Please review (and merge if you want to accept) PR #65 before merging in this one, because this one contains all the commits also done in PR #65.

In addition to the changes in PR #64, this PR **publishes** reports from:
- static analysis
- code coverage
- doxygen documentation (only with pushes to the master branch)

on a github pages site. Currently this is at: <https://wtoorop.github.io/ithipages>

We could change that location into for example: <https://private-octopus.github.io/ithipages> or <https://private-octopus.github.io/ithi-reports> , but for that you will have to add a repository and enable GitHub pages (it is on the Settings -> Options page, somewhere near the bottom)

If you give me access to that repository I can setup the key to publish from travis.  Or you can do that yourself.  I followed the procedure described in:  https://blog.ionelmc.ro/2015/07/11/publishing-to-github-pages-from-travis-ci/

### CODE REVIEW

**Comment by huitema** [comment]
I have created the repo at https://private-octopus.github.io/ithitools/. You have collaborator access to the ithitools project. What else do we need?

**Comment by wtoorop** [comment]
I would prefer a different repository than private-octopus/ithitools , because we need to authorize our (own) travis job to push to the repository where the reports will be published.

How about private-octopus/ithi-reports ?

There is no rush either.  We could sit down together at IETF and setup the authorization bits...

**Comment by huitema** [comment]
It turns out that I won't be at the IETF next week. My wife's brother
passed away, and I will be traveling to France instead of Montreal.
Let's do a conference call after the 24.

-- Christian Huitema

**Comment by wtoorop** [comment]
Reports are now pushed to https://private-octopus.github.io/ithipages/#code-analysis-reports
This PR is ready to be merged now

**Pull request merged**
