### PR TITLE
Fix a number of warnings from the gcc compiler.

### PR DESCRIPTION
**Pull request by huitema**
I noticed a number of warnings in the travis logs, so here is a batch of fixes.

### CODE REVIEW

**Comment by wtoorop** [comment]
Excellent, Thanks!
Yes I enabled extra warning flags in .travis.yml .  Attending to those will be one of my suggestions ;)
I noticed that the OS X machines sometimes fail the publish test b.t.w.
Probably because of uninitialized value.
valgrind shows these:
```
Starting test 16 (publish)
==4378== Conditional jump or move depends on uninitialised value(s)
==4378==    at 0x1C85D7: ithipublisher::ParseFileName(_MetricFileHolder*, char const*, int) (ithipublisher.cpp:227)
==4378==    by 0x1C76D6: ithipublisher::CollectMetricFiles() (ithipublisher.cpp:100)
==4378==    by 0x20E5B9: PublishTest::DoOneTest(int, char const**, unsigned long, char const*, char const*) (PublishTest.cpp:128)
==4378==    by 0x20EA1B: PublishTest::DoTest() (PublishTest.cpp:177)
==4378==    by 0x1AB74F: do_one_test(int, _IO_FILE*) (ithitest.cpp:51)
==4378==    by 0x1ABB34: main (ithitest.cpp:99)
```

**Comment by huitema** [comment]
Yes, I am also seeing a failure on the publish test in some batches. Investigating.

**Comment by wtoorop** [comment]
I guess `file->file_name` on line 227 of  `ithipublisher.cpp` should be replaced with `name`...

**Comment by huitema** [comment]
Not checking this yet -- still a number of warning to find out. Will see to that tomorrow.

**Comment by huitema** [comment]
All warnings fixed. All tests pass. I fixed the config.h reference for windows builds, and the file name issue that cause valgrind to complain. I found one actual bug when fixing the warnings: return function for the "get tld" method was not set correctly, and the method was giving improper results when sending a query to the root. When parsing queries for ".", the TLD was set to a random value. This caused bogus domains to be inserted in the frequent TLD list, but since we only retain the frequently used values this had little effect. On the other hand, because each query to root was counted a query to a different random domain, they were all considered useful, and that caused an underestimation of the number on useless repeat queries. Not by much, but still 1 or 2 %. Glad that we fixed that.

**Comment by wtoorop** [comment]
Thanks Christian, Sorry to cause all this work, but I'm glad some good came out of it too :)

**Pull request merged**
